In [35]:
import numpy as np
import pandas as pd

## Datatypes & Attributes

In [28]:
# 1-dimensonal array, also referred to as a vector
a1 = np.array([1, 2, 3])

# 2-dimensional array, also referred to as matrix
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

# 3-dimensional array, also referred to as a matrix
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])

In [34]:
type(a1), type(a2), type(a1)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [30]:
a1.shape

(3,)

In [31]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [32]:
a3.dtype

dtype('int32')

In [33]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [36]:
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating Arrays

In [38]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [42]:
ones = np.ones((2,3))

In [43]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [46]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [49]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [51]:
random_array = np.random.randint(0, 10, size=(3,5))
random_array

array([[6, 4, 9, 7, 7],
       [2, 2, 0, 6, 8],
       [2, 3, 9, 6, 1]])

In [52]:
random_array.size, random_array.shape

(15, (3, 5))

In [59]:
np.random.random((3,5)) 

array([[0.51449378, 0.91116979, 0.7328502 , 0.50488337, 0.89264384],
       [0.78538587, 0.05591858, 0.26864936, 0.15197539, 0.76223165],
       [0.98105448, 0.83376134, 0.18137807, 0.98694266, 0.46809952]])

In [60]:
np.random.rand(3,5)

array([[0.55226725, 0.81957735, 0.21604749, 0.12570318, 0.97370119],
       [0.84046974, 0.32817893, 0.39660241, 0.69275995, 0.05311672],
       [0.26032537, 0.11786248, 0.02704985, 0.45818717, 0.77236849]])

## 4. manipulating & comparing numpy array

Arithmetic

In [61]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [62]:
a1+ones

array([2., 3., 4.])

In [66]:
a1 - ones

array([0., 1., 2.])

In [73]:
a1

array([1, 2, 3])

In [79]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [80]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [76]:
a1*a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

## Aggregation
performing the same operation on a number of things

In [82]:
listy_list = [1,2,3]

In [83]:
sum(listy_list)

6

In [84]:
sum(a1)

6

In [85]:
np.sum(a1)

6

In [86]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [87]:
np.mean(a2)

3.6333333333333333

In [88]:
np.max(a2)

6.5

In [89]:
np.min(a2)

1.0

In [91]:
np.std(a2)

1.8226964152656422

In [92]:
np.var(a2)

3.3222222222222224